F1=int(raw_input("enter the temperature in fahrenheit: "))
C1=(F1-32)*(5/9)
print "temperature in celsius :%d"%(C1)
C2=int(raw_input("enter the temperature in celsius: "))
F2=(C2*(9/5)+32)
print "temperature in celsius :%d"%(F2)